[package]
name = "prepatory"
version = "0.1.0"
edition = "2024"

[dependencies]
# tokio = { version = "1.45.1", features = ["sync", "rt", "macros", "net"] }
tokio = { version = "1.45.1", features = ["full"] }
rand = "0.8.5"
indexmap = "2.9.0"
